POST localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "First published Post",
  "content": "This is the content of my first post. It must be at least 10 characters long.",
  "description": "hallo this is long description",
  "category": {
    "name": "First Category"
  },
  "tags":[{
      "name": "First Tag"
    },
    {
    "name": "Second Tag"
  }]
   ,
  "status": "PUBLISHED"
}

> {%
    // Store postId from JSON response
    client.global.set("postId", response.body.id);
%}
