"use client";

import { useEffect, useState } from "react";
import { useInView } from "react-intersection-observer";
// Import types generated by Orval
import { PostWithBookmarkResponse, UserResponse } from "@/api/generated/model";
import { fetchPostsPage } from "@/lib/actions/posts/action";
import { Loader2 } from "lucide-react";
import { PostCard } from "./PostCard";

interface PostsGridProps {
  initialPosts: PostWithBookmarkResponse[] | null; // Use Orval types
  currentUser: UserResponse | null;
}

export function PostsGrid({ initialPosts, currentUser }: PostsGridProps) {
  // Safe initialization
  const [posts, setPosts] = useState<PostWithBookmarkResponse[]>(
    initialPosts || []
  );

  // Start at page 1 because page 0 was passed as initialPosts
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);

  const { ref, inView } = useInView({
    threshold: 0,
    rootMargin: "200px",
  });

  const loadMorePosts = async () => {
    if (!hasMore) return;

    // Call the Server Action (which uses Orval)
    const newPosts = await fetchPostsPage(page);

    if (newPosts && newPosts.length > 0) {
      setPosts((prev) => [...prev, ...newPosts]);
      setPage((prev) => prev + 1);
    } else {
      setHasMore(false);
    }
  };

  useEffect(() => {
    if (inView && hasMore) {
      loadMorePosts();
    }
  }, [inView, hasMore]);

  return (
    <div className="gap-6 flex flex-col pb-10">
      {posts.map((postWithBookMark, index) => {
        if (!postWithBookMark?.post) return null;

        // Prefer ID, fallback to index
        const key = postWithBookMark.post.id || index;

        return (
          <PostCard
            key={key}
            postWithBookMark={postWithBookMark}
            currentUser={currentUser}
          />
        );
      })}

      {hasMore && (
        <div ref={ref} className="flex justify-center items-center py-6">
          <Loader2 className="h-6 w-6 animate-spin text-gray-400" />
        </div>
      )}

      {!hasMore && posts.length > 0 && (
        <div className="text-center py-6 text-gray-400 text-sm">
          You've reached the end.
        </div>
      )}
    </div>
  );
}
