import Navbar from "@/components/navbar/Navbar";
import { MenuSidebar } from "@/components/sidebar/MenuSidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

// ✅ 1. Import the Providers component
import { Providers } from "../components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} min-h-screen bg-white text-black`}
      >
        {/* ✅ 2. Wrap EVERYTHING inside Providers */}
        <Providers>
          <SidebarProvider defaultOpen={false}>
            <MenuSidebar />
            <SidebarInset>
              <Navbar />
              <main>
                {/* 'children' here contains FeedTabs (Server Component).
                  It passes through the Providers without losing its server-side rendering.
                */}
                {children}
              </main>
            </SidebarInset>
          </SidebarProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
