POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "beki32@gmail.com",
  "name": "bekir2",
  "password": "password",
  "profileImageUrl": ""
}

> {%
    // Store token from JSON response
    client.global.set("access_token", response.body.token);

    // Extract cookie from response headers
    const cookieHeader = response.headers.valueOf("Set-Cookie");
    if (cookieHeader) {
        // Assuming you want the first cookie or a specific one; adjust as needed
        client.global.set("refresh_token", cookieHeader);
    }
%}